"use client";

import React from "react";
import { Wallet } from "lucide-react";
import { useDeviceType } from "@/hooks/useDeviceType";

interface AddToGoogleWalletProps {
  /** The "Save to Google Wallet" URL generated by your backend (a signed JWT link). */
  saveUrl: string;
  /** Optional override for what iOS users see. Pass `null` to render nothing on iOS. */
  iosFallback?: React.ReactNode;
  className?: string;
}

/**
 * Renders an "Add to Google Wallet" button — but only on Android, where Google
 * Wallet is supported. On iOS it shows an alternative message (or nothing), and
 * before device detection resolves it renders nothing to avoid a hydration flash.
 */
export function AddToGoogleWallet({
  saveUrl,
  iosFallback,
  className = "",
}: AddToGoogleWalletProps) {
  const device = useDeviceType();

  // Hidden until the server side is configured, so the button is never broken.
  // Flip NEXT_PUBLIC_GOOGLE_WALLET_ENABLED to "true" once the API env vars are set.
  if (process.env.NEXT_PUBLIC_GOOGLE_WALLET_ENABLED !== "true") return null;

  // Not resolved yet (server / first client render) — render nothing.
  if (device === "unknown") return null;

  // iOS (and anything non-Android): Google Wallet isn't available.
  if (device !== "android") {
    if (device === "ios") {
      return (
        iosFallback ?? (
          <p className={`text-center text-xs text-muted-foreground ${className}`}>
            Google Wallet isn&apos;t available on iOS — use &ldquo;Save Pass to Phone&rdquo; instead.
          </p>
        )
      );
    }
    // Desktop / other: hide the button entirely.
    return null;
  }

  // Android only.
  return (
    <a
      href={saveUrl}
      target="_blank"
      rel="noopener noreferrer"
      className={`flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#202124] text-sm font-medium text-white transition hover:bg-black ${className}`}
    >
      <Wallet className="h-4 w-4" />
      Add to Google Wallet
    </a>
  );
}
